-- Opt-in simulated portfolio data. Password hash is bound separately by DemoSeeder.
INSERT INTO app_user(id,email,name,password_hash,role,created_at,demo)
SELECT md5('fitplix-demo-'||n)::uuid,case n when 1 then 'admin@fitplix.local' when 2 then 'demo@fitplix.local' else 'demo'||n||'@fitplix.local' end,
case n when 1 then 'Demo Product Manager' when 2 then 'Alex Morgan' else 'Demo Member '||n end,'PENDING',case when n=1 then 'ADMIN' else 'USER' end,
(current_date-(case when n=1 then 89 else 90-n*3 end))::timestamp at time zone 'UTC'+interval '6 hours',true FROM generate_series(1,30) n ON CONFLICT DO NOTHING;
INSERT INTO visitor(id,first_seen,user_id,demo) SELECT md5('fitplix-visitor-'||n)::uuid,(current_date-(90-(n%30+1)*3))::timestamp at time zone 'UTC'+interval '5 hours',case when n<=30 then md5('fitplix-demo-'||n)::uuid else null end,true FROM generate_series(1,60) n ON CONFLICT DO NOTHING;
UPDATE visitor v SET first_seen=u.created_at-interval '1 hour' FROM app_user u WHERE v.user_id=u.id AND v.demo;
INSERT INTO user_profile(user_id,age,sex,height,weight,start_weight,target_weight,activity,goal,diet,water_target,calorie_target,protein_target,carbs_target,fat_target,fiber_target,timezone)
SELECT md5('fitplix-demo-'||n)::uuid,23+n%15,'MALE',170+n%12,74+n%8,78+n%8,70+n%8,'MODERATE','LOSE','ANY',2500,2200,130,262,70,30,'UTC' FROM generate_series(1,27)n ON CONFLICT DO NOTHING;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(u.id::text||'-registered')::uuid,u.id,'USER_REGISTERED',u.created_at,'{"simulated":true}' FROM app_user u WHERE demo ON CONFLICT DO NOTHING;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(u.id::text||'-'||event)::uuid,u.id,event,u.created_at+case event when 'ONBOARDING_COMPLETED' then interval '5 minutes' else interval '6 minutes' end,'{"simulated":true}' FROM app_user u JOIN user_profile p ON p.user_id=u.id CROSS JOIN (VALUES('ONBOARDING_COMPLETED'),('CALORIE_GOAL_GENERATED')) e(event) WHERE u.demo ON CONFLICT DO NOTHING;
INSERT INTO experiment_assignment(id,user_id,experiment_id,variant,assigned_at) SELECT md5(u.id::text||'-experiment')::uuid,u.id,'onboarding-insight-v1',case when ascii(substr(u.id::text,1,1))%2=0 then 'A' else 'B' end,u.created_at+interval '6 minutes' FROM app_user u JOIN user_profile p ON p.user_id=u.id WHERE demo ON CONFLICT DO NOTHING;
CREATE TEMP TABLE demo_days AS SELECT md5('fitplix-demo-'||n)::uuid user_id,n,(current_date-d) date,d FROM generate_series(1,25)n CROSS JOIN generate_series(0,89)d JOIN app_user u ON u.id=md5('fitplix-demo-'||n)::uuid WHERE (current_date-d)>=(u.created_at at time zone 'UTC')::date AND (n<=3 OR (n+d)%case when n<=15 then 8 else 3 end<>0) AND NOT(n>20 AND d<14);
INSERT INTO daily_target(id,user_id,date,calories,protein,carbs,fat,fiber,water) SELECT md5(user_id::text||date||'-target')::uuid,user_id,date,2200,130,262,70,30,2500 FROM demo_days ON CONFLICT DO NOTHING;
INSERT INTO meal(id,user_id,date,meal_type,created_at) SELECT md5(user_id::text||date||slot)::uuid,user_id,date,slot,date::timestamp at time zone 'UTC'+case slot when 'BREAKFAST' then interval '8 hours' when 'LUNCH' then interval '13 hours' else interval '18 hours' end FROM demo_days CROSS JOIN (VALUES('BREAKFAST'),('LUNCH'),('DINNER'))slots(slot) ON CONFLICT DO NOTHING;
INSERT INTO meal_item(id,meal_id,food_id,name,grams,calories,protein,carbs,fat,fiber,sugar,sodium,incomplete)
SELECT md5(m.id::text||f.id)::uuid,m.id,f.id,f.name,portion.g,f.calories*portion.g/100,f.protein*portion.g/100,f.carbs*portion.g/100,f.fat*portion.g/100,coalesce(f.fiber,0)*portion.g/100,coalesce(f.sugar,0)*portion.g/100,coalesce(f.sodium,0)*portion.g/100,f.fiber is null or f.sugar is null or f.sodium is null
FROM meal m JOIN app_user u ON u.id=m.user_id CROSS JOIN LATERAL (SELECT unnest(case m.meal_type when 'BREAKFAST' then ARRAY[173944,171265,168138] when 'LUNCH' then ARRAY[168878,171477] else ARRAY[172421,168878,171477] end) fid) selection JOIN food f ON f.id=selection.fid CROSS JOIN LATERAL (SELECT (case f.id when 173944 then 120 when 171265 then 250 when 168138 then 90 when 168878 then 200 when 171477 then 140 else 220 end)*(0.85+((extract(day from m.date)::int+ascii(substr(m.user_id::text,1,1)))%5)*.08) g)portion WHERE u.demo ON CONFLICT DO NOTHING;
INSERT INTO water_entry(id,user_id,date,ml) SELECT md5(user_id::text||date||'-water')::uuid,user_id,date,1500+(n+d)%7*250 FROM demo_days ON CONFLICT DO NOTHING;
INSERT INTO activity_entry(id,user_id,date,steps,minutes) SELECT md5(user_id::text||date||'-activity')::uuid,user_id,date,3500+(n+d)%10*800,15+(n+d)%5*10 FROM demo_days ON CONFLICT DO NOTHING;
INSERT INTO weight_entry(id,user_id,date,kg) SELECT md5(dd.user_id::text||dd.date||'-weight')::uuid,dd.user_id,dd.date,p.start_weight-((dd.date-(u.created_at at time zone 'UTC')::date)*.045)+((dd.n+dd.d)%3)*.15 FROM demo_days dd JOIN user_profile p ON p.user_id=dd.user_id JOIN app_user u ON u.id=dd.user_id WHERE dd.d%7=0 OR dd.d=0 ON CONFLICT DO NOTHING;
UPDATE user_profile p SET weight=w.kg FROM (SELECT DISTINCT ON (user_id) user_id,kg FROM weight_entry ORDER BY user_id,date DESC)w JOIN app_user u ON u.id=w.user_id WHERE p.user_id=w.user_id AND u.demo;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(m.id::text||'-event')::uuid,m.user_id,'MEAL_LOGGED',m.created_at,'{"simulated":true}' FROM meal m JOIN app_user u ON u.id=m.user_id WHERE u.demo ON CONFLICT DO NOTHING;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(user_id::text||date||event)::uuid,user_id,event,date::timestamp at time zone 'UTC'+interval '20 hours','{"simulated":true}' FROM demo_days CROSS JOIN (VALUES('USER_LOGIN'),('WATER_LOGGED'),('ACTIVITY_LOGGED'))e(event) ON CONFLICT DO NOTHING;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(user_id::text||date||'-weight-event')::uuid,user_id,'WEIGHT_UPDATED',date::timestamp at time zone 'UTC'+interval '20 hours','{"simulated":true}' FROM weight_entry w JOIN app_user u ON u.id=w.user_id WHERE u.demo ON CONFLICT DO NOTHING;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(user_id::text||date||'-analytics')::uuid,user_id,'ANALYTICS_VIEWED',date::timestamp at time zone 'UTC'+interval '20 hours','{"simulated":true}' FROM demo_days WHERE (n+d)%3=0 ON CONFLICT DO NOTHING;
INSERT INTO saved_meal(id,user_id,name,meal_type,items,planned_date,created_at) SELECT md5(user_id::text||'-plan')::uuid,user_id,'Rice & lentil bowl','LUNCH','[{"foodId":168878,"grams":180},{"foodId":172421,"grams":220}]',current_date,u.created_at+interval '2 days' FROM user_profile p JOIN app_user u ON u.id=p.user_id WHERE u.demo AND extract(day from u.created_at)::int%2=0 ON CONFLICT DO NOTHING;
INSERT INTO analytics_event(id,user_id,event_name,occurred_at,metadata) SELECT md5(s.id::text||'-event')::uuid,s.user_id,'MEAL_PLAN_CREATED',s.created_at,'{"simulated":true}' FROM saved_meal s JOIN app_user u ON u.id=s.user_id WHERE u.demo ON CONFLICT DO NOTHING;
DROP TABLE demo_days;
